name: EC2 Deployment Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production   # 👈 use environment secrets

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}   # private key for EC2 login
          script_stop: true                 # 👈 stop if any command fails
          script: |
            set -e  # fail on first error
            echo "[INFO] Loading environment..."
            source ~/.bashrc || true
            source ~/.profile || true
            export PATH=$PATH:$(npm bin -g)

            echo "[INFO] Switching to app directory..."
            cd ~/mtc_production/mtc-api-node || { echo "[ERROR] Directory not found"; exit 1; }

            echo "[INFO] Pulling latest code..."
            if ! git pull origin main; then
              echo "[ERROR] Git pull failed"; exit 1;
            fi

            echo "[INFO] Installing dependencies..."
            if ! npm install --no-audit --no-fund; then
              echo "[ERROR] NPM install failed"; exit 1;
            fi

            echo "[INFO] Updating environment file..."
            if [ -f env.production.template ]; then
              cp env.production.template .env.ec2
              echo "[INFO] .env.ec2 updated successfully"
            else
              echo "[ERROR] env.production.template missing"; exit 1;
            fi

            echo "[INFO] Managing PM2 service..."
            if pm2 list | grep -q "mtc_backend"; then
              echo "[INFO] Restarting existing service..."
              pm2 restart mtc_backend || { echo "[ERROR] PM2 restart failed"; exit 1; }
            else
              echo "[INFO] Starting new PM2 service..."
              pm2 start npm --name "mtc_backend" -- run dev || { echo "[ERROR] PM2 start failed"; exit 1; }
              pm2 save
            fi

            echo "[INFO] Checking PM2 status..."
            pm2 show mtc_backend || { echo "[ERROR] PM2 service not found"; exit 1; }

            echo "[INFO] Deployment finished ✅"
            exit 0
